@startuml Adapter
    skinparam classAttributeIconSize 0
    
    class Cliente {
        +doSomething() : void
    }

    interface Target {
        +request() : void
    }

    class Adapter {
        +request() : void
    }

    class Adaptee {
        +specificRequest() : void
    }

    Cliente -right-> Target : uses
    Target <|.. Adapter
    Adapter ..> Adaptee : adapts
    note right of Adapter : Adapta Adaptee para Target
@enduml
