@startuml ChainOfResponsibilityWithClient
    skinparam classAttributeIconSize 0

    interface Handler <<interface>> {
        +handleRequest() : void
        -successor : Handler
    }

    class ConcreteHandler1 {
        +handleRequest() : void
    }

    class ConcreteHandler2 {
        +handleRequest() : void
    }

    class Client {
        +makeRequest() : void
    }

    Handler <|.. ConcreteHandler1
    Handler <|.. ConcreteHandler2
    Handler ..> Handler : next
    Client -> Handler : sends request
    note right of Handler : Pode ter um sucessor na cadeia
@enduml
